# StatefulSet Postgres Database
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonar-postgres-dep
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-postgres
  template:
    metadata:
      name: sonar-postgres-dep
      labels:
        app: sonar-postgres
    spec:
      containers:
        - image: postgres:latest
          name: sonar-postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: POSTGRES_USER
              value: sonar
          ports:
            - containerPort: 5432
              name: postgresport
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: sonar-postgres-pvc

#Service for Postgres Database            
---
apiVersion: v1
kind: Service
metadata:
  namespace: devops-tools
  name: sonar-postgres
spec:
  selector:
    app: sonar-postgres
  ports:
    - port: 5432

#Persistent Volume and Persistent Volume Claim for Postgres Database
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: devops-tools
  name: sonar-postgres-pv
  labels:
    type: local
    app: sonar-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/sonar-postgres

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: devops-tools
  name: sonar-postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

#SonarQube Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      name: sonarqube
      labels:
        app: sonarqube
    spec:
      containers:
        - image: sonarqube:latest
          args:
            - -Dsonar.web.context=/sonar
          name: sonarqube
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd #kubectl create secret generic postgres-pwd --from-literal=password=CodeRise_Pass
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-postgres:5432/sonar
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  namespace: devops-tools
  name: sonarqube-service
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      nodePort: 31002