kind: Namespace
apiVersion: v1
metadata:
  name: gitlab

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab-deployment
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      name: gitlab-dep-pod
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/opt/gitlab
            name: data
          - mountPath: /etc/gitlab
            name: config
      volumes:
        - name: data
          hostPath:
            path: /home/data/var/opt/gitlab
            type: Directory
        - name: config
          hostPath:
            path: /home/data/etc/gitlab
            type: Directory
          

---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80