kind: Namespace
apiVersion: v1
metadata:
  name: gitlab

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab-deployment
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      name: gitlab-dep-pod
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80