#Persistent Volume and Persistent Volume Claim for SonarQube
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: devops-tools
  name: sonar-pv
  labels:
    type: local
    app: sonarqube
spec:
  storageClassName: local-storage
  claimRef:
    name: sonar-pvc
    namespace: devops-tools
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /home/data/sonar
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-worker

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: devops-tools
  name: sonar-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi