
## To create namespace
kind: Namespace
apiVersion: v1
metadata:
  name: devops-tools

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins-dep-pod
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-var-jenkins

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      nodePort: 31001
      port: 8080

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-var-jenkins
  namespace: devops-tools
  labels:
    app: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/data/jenkins

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-var-jenkins
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi